/* 
 * Operating Systems   (2INCO)   Practical Assignment
 * Condition Variables Application
 *
 * STUDENT_NAME_1 (STUDENT_NR_1)
 * STUDENT_NAME_2 (STUDENT_NR_2)
 *
 * Grading:
 * Students who hand in clean code that fully satisfies the minimum requirements will get an 8. 
 * "Extra" steps can lead to higher marks because we want students to take the initiative. 
 * Extra steps can be, for example, in the form of measurements added to your code, a formal 
 * analysis of deadlock freeness etc.
 */
 
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <pthread.h>

#include "prodcons.h"

/* buffer[]
 * circular buffer that holds the items generated by the producer and
 * which have to be retrieved by consumers
 */
static ITEM   buffer [BUFFER_SIZE];
pthread_mutex_t bufferMutex = PTHREAD_MUTEX_INITIALIZER;
static pthread_cond_t condition = PTHREAD_COND_INITIALIZER;


static void rsleep (int t);



/* producer thread */
static void * producer (void * arg)
{
    ITEM    item;   // a produced item
    int itemsProduced = 1;
    
    while (itemsProduced < NROF_ITEMS)/*TODO: not all items produced*/
    {
        rsleep (PRODUCER_SLEEP_FACTOR);
        
        int randomDestination = (rand() % NROF_CONSUMERS) + 1;
        itemsProduced <<= NROF_BITS_DEST;
        item = itemsProduced & randomDestination;
        itemsProduced++;

        pthread_mutex_lock(&bufferMutex);
        printf("thread: enter CS\n");

        while(){
        	printf("thread: wait...\n");
        	pthread_cond_wait(&condition, &bufferMutex);
        }
        printf("thread:signalled\n");
        printf("thread: leave CS\n");
        pthread_mutex_unlock(&bufferMutex);
        // TODO: 
        // * produce new item and put it into buffer[]
        //
        // use shifting and masking to put a 'seq' and a 'dest' in an item
        // (see mask_test() in condition_basics.c how to create bit masks)
        //
        // follow this pseudocode (according to the ConditionSynchronization lecture):
        //      mutex-lock;
        //      while not condition-for-this-producer
        //          wait-cv;
        //      critical-section;
        //      possible-cv-signals;
        //      mutex-unlock;
        //
        // (see condition_test() in condition_basics.c how to use condition variables)

        // apply this printf at the correct location in that pseudocode:
        printf("%04x\n", item); // write info to stdout
    }
    
    // TODO: 
    // * inform consumers that we're ready
}

/* consumer thread */
static void * consumer (void * arg)
{
    ITEM    item;   // a consumed item
    int     id;     // identifier of this consumer (value 0..NROF_CONSUMERS-1)
    
    while (1/* TODO: not all items retrieved for this customer */)
    {
        rsleep (100 * NROF_CONSUMERS);

        // TODO: get the next item from buffer[] (intended for this customer)
        //
        // follow this pseudocode (according to the ConditionSynchronization lecture):
        //      mutex-lock;
        //      while not condition-for-this-consumer
        //          wait-cv;
        //      critical-section;
        //      possible-cv-signals;
        //      mutex-unlock;

        // apply this printf at the correct location in that pseudocode:
        printf("%*s    C%d:%04x\n", 7*id, "", id, item); // write info to stdout (with indentation)
    }
}

int main (void)
{
    // TODO: 
    // * startup the producer thread and the consumer threads
    // * wait until all threads are finished  
    // (see assignment Threaded Application how to create threads and how to wait for them)
    
    return (0);
}

/*
 * rsleep(int t)
 *
 * The calling thread will be suspended for a random amount of time between 0 and t microseconds
 * At the first call, the random generator is seeded with the current time
 */
static void rsleep (int t)
{
    static bool first_call = true;
    
    if (first_call == true)
    {
        srandom (time (NULL) % getpid ());
        first_call = false;
    }
    usleep (random() % t);
}

